### ISSUE TITLE
MDEV-5458 temporal/temporal_functions.yy fails at sec_since_epoch(int, int, int, int, int, int)::__PRETTY_FUNCTION__ in sql/tztime.cc:799

### ISSUE THREAD

**Issue by joel9001** [Tokutek/mariadb-5.5#28]
```
Program terminated with signal 6, Aborted.
#0  0x00007f6f9581cf2c in __pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:62
#0  0x00007f6f9581cf2c in __pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:62
#1  0x0000000000b91c63 in my_write_core (sig=6) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/mysys/stacktrace.c:457
#2  0x00000000006f78ca in handle_fatal_signal (sig=6) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/signal_handler.cc:264
#3  <signal handler called>
#4  0x00007f6f94e76037 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#5  0x00007f6f94e79698 in __GI_abort () at abort.c:90
#6  0x00007f6f94e6ee03 in __assert_fail_base (fmt=0x7f6f94fc6158 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xc3c2a0 "mon > 0 && mon < 13", file=file@entry=0xc3c3a0 "/home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/tztime.cc", line=line@entry=799, function=function@entry=0xc3cbc0 <sec_since_epoch(int, int, int, int, int, int)::__PRETTY_FUNCTION__> "my_time_t sec_since_epoch(int, int, int, int, int, int)") at assert.c:92
#7  0x00007f6f94e6eeb2 in __GI___assert_fail (assertion=0xc3c2a0 "mon > 0 && mon < 13", file=0xc3c3a0 "/home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/tztime.cc", line=799, function=0xc3cbc0 <sec_since_epoch(int, int, int, int, int, int)::__PRETTY_FUNCTION__> "my_time_t sec_since_epoch(int, int, int, int, int, int)") at assert.c:101
#8  0x000000000064b7b6 in sec_since_epoch (year=2008, mon=0, mday=0, hour=7728, min=0, sec=0) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/tztime.cc:799
#9  0x000000000064bb27 in TIME_to_gmt_sec (error_code=0x7f6f77ff817c, sp=0x7f6f7a6f6408, t=0x7f6f77ff81f0) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/tztime.cc:942
#10 Time_zone_db::TIME_to_gmt_sec (this=<optimized out>, t=0x7f6f77ff81f0, error_code=0x7f6f77ff817c) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/tztime.cc:1261
#11 0x0000000000794f80 in Item_func_convert_tz::get_date (this=0x7f6f63e08910, ltime=0x7f6f77ff81f0, fuzzy_date=<optimized out>) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/item_timefunc.cc:1974
#12 0x0000000000729a86 in get_datetime_value (thd=thd@entry=0x7f6f80feb060, item_arg=item_arg@entry=0x7f6f77ff8298, cache_arg=cache_arg@entry=0x7f6f77ff8290, warn_item=0x7f6f63e08910, is_null=is_null@entry=0x7f6f77ff828f) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/item_cmpfunc.cc:902
#13 0x0000000000729e93 in Item_func_between::val_int (this=0x7f6f63e08a08) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/item_cmpfunc.cc:2265
#14 0x000000000070a437 in Item::val_bool (this=0x7f6f63e08a08) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/item.cc:215
#15 0x00000000007236bf in Item_cond_and::val_int (this=0x7f6f63dd0208) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/item_cmpfunc.cc:4692
#16 0x00000000006f5f17 in skip_record (this=<optimized out>, thd=<optimized out>) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/opt_range.h:1013
#17 find_all_keys (tempfile=0x7f6f77ff8680, buffpek_pointers=0x7f6f77ff8810, sort_keys_buf=0x7f6f63e78060 '\245' <repeats 4949 times>, "h4z\025", '\245' <repeats 3143 times>, 'Z' <repeats 32768 times>, "\200\032\310co\177", sort_keys=0x7f6f63e78060, select=0x7f6f63dd0348, param=0x7f6f77ff8600) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/filesort.cc:630
#18 filesort (thd=thd@entry=0x7f6f80feb060, table=table@entry=0x7f6f76d0d460, sortorder=0x7f6f00000000, s_length=1993397344, select=select@entry=0x7f6f63dd0348, max_rows=18446744069414584320, max_rows@entry=18446744073709551615, sort_positions=sort_positions@entry=false, examined_rows=examined_rows@entry=0x7f6f77ff8e58) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/filesort.cc:240
#19 0x00000000005e5abb in create_sort_index (thd=0x7f6f80feb060, join=join@entry=0x7f6f63e090c8, order=<optimized out>, filesort_limit=18446744073709551615, select_limit=18446744073709551615, is_order_by=false) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_select.cc:19689
#20 0x00000000005f3a23 in JOIN::exec (this=this@entry=0x7f6f63e090c8) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_select.cc:2829
#21 0x00000000005f4866 in mysql_select (thd=thd@entry=0x7f6f80feb060, rref_pointer_array=rref_pointer_array@entry=0x7f6f80feecc8, tables=0x7f6f63cb9b50, wild_num=0, fields=..., conds=0x7f6f63cbab18, og_num=2, order=0x7f6f63e08e40, group=0x0, having=0x0, proc_param=0x0, select_options=select_options@entry=2147748608, result=result@entry=0x7f6f63e090a8, unit=unit@entry=0x7f6f80fee388, select_lex=select_lex@entry=0x7f6f80feea60) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_select.cc:3079
#22 0x00000000005f88a8 in handle_select (thd=thd@entry=0x7f6f80feb060, lex=lex@entry=0x7f6f80fee2d8, result=result@entry=0x7f6f63e090a8, setup_tables_done_option=setup_tables_done_option@entry=0) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_select.cc:318
#23 0x000000000059ac8a in execute_sqlcom_select (thd=thd@entry=0x7f6f80feb060, all_tables=0x7f6f63cb9b50) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_parse.cc:4701
#24 0x00000000005a0bb8 in mysql_execute_command (thd=thd@entry=0x7f6f80feb060) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_parse.cc:2234
#25 0x00000000005a84f7 in mysql_parse (thd=thd@entry=0x7f6f80feb060, rawbuf=<optimized out>, length=<optimized out>, parser_state=parser_state@entry=0x7f6f77ffa5f0) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_parse.cc:5812
#26 0x00000000005a908a in dispatch_command (command=command@entry=COM_QUERY, thd=thd@entry=0x7f6f80feb060, packet=packet@entry=0x7f6f80f75061 " SELECT `pk` AS c1 , TIMESTAMP( `col_date_nokey` ) AS c2 , `col_date_nokey` AS c3 , `col_datetime_nokey` AS c4 FROM `BB` WHERE FROM_DAYS( `col_int_nokey` ) IS NOT NULL AND `col_time_key` NOT IN ( TIMESTAMP( CURRENT_DATE() ) , UTC_DATE() , DATE( '2004-10-25' ) ) AND `col_date_nokey`  BETWEEN `pk` AND CONVERT_TZ( GREATEST( `col_varchar_key` , `col_time_nokey` , '2007-12-22' , '0000-00-00' , `col_date_key` ) , 'leap/Europe/Moscow' , 'Japan' ) AND LOCALTIME() IS NOT NULL ORDER BY `pk` , `col_varchar_nokey`", packet_length=packet_length@entry=507) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_parse.cc:1082
#27 0x00000000005aaa16 in do_command (thd=0x7f6f80feb060) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_parse.cc:797
#28 0x000000000066b82e in do_handle_one_connection (thd_arg=thd_arg@entry=0x7f6f80feb060) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_connect.cc:1266
#29 0x000000000066b920 in handle_one_connection (arg=0x7f6f80feb060) at /home/tokubuild/builds/build-tokudb-1386719273-debug-e/mariadb-5.5.34/sql/sql_connect.cc:1181
#30 0x00007f6f95817f8e in start_thread (arg=0x7f6f77ffb700) at pthread_create.c:311
#31 0x00007f6f94f39a0d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by joel9001** [comment]
The temporal/temporal_functions.yy RQG test induces a crash with the following command:

./runall.pl --grammar=conf/temporal/temporal_functions.yy --duration=300 --queries=10000000 --threads=64 --basedir=/data/mysql/mariadb-5.5.34-tokudb-1386719273-debug-e-linux-x86_64 --vardir=/data/mysql/temporal_functions_vardir --mysqld=--default-storage-engine=TokuDB --mysqld=--general_log

**Comment by prohaska** [comment]
crashes with innodb.

/runall.pl --grammar=conf/temporal/temporal_functions.yy --duration=300 --queries=10000000 --threads=1 --basedir=/home/prohaska/ma5534/install --vardir=/home/prohaska/vardir_ma5534_temporal_functions_innodb_1 --mysqld=--default-storage-engine=innodb --mysqld=--general_log

**Comment by prohaska** [comment]
crashes with mariadb's version of 5.5.34
