### ISSUE TITLE
cmdtrace163 crashes tokudb while running alter table add primary key with dup key error

### ISSUE THREAD

**Issue by prohaska** [Tokutek/mariadb-5.5#45]
the ft loader called the tokudb handler with an empty key.  there are 2 bugs.  the tokudb handler crashes if it tries to decode an empty key.  the ft loader passes the tokudb handler an empty key.

```
Program terminated with signal 11, Segmentation fault.
(gdb) bt
#0  0x000000328bc0be32 in pthread_kill () from /lib64/libpthread.so.0
#1  0x0000000000b878b3 in my_write_core (sig=11) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/mysys/stacktrace.c:457
#2  0x00000000006ecdfa in handle_fatal_signal (sig=11) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/signal_handler.cc:264
#3  <signal handler called>
#4  unpack_toku_int (num_bytes=4, from_tokudb=0x1 <Address 0x1 out of bounds>, to_mysql=0x2aead044258b "") at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/hatoku_c\
mp.cc:400
#5  unpack_toku_key_field (key_part_length=4, field=0x2aead1bb2db8, from_tokudb=0x1 <Address 0x1 out of bounds>, to_mysql=0x2aead044258b "") at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mari\
adb-5.5.35/storage/tokudb/hatoku_cmp.cc:1514
#6  ha_tokudb::place_key_into_mysql_buff (this=this@entry=0x2aeadafc7078, key_info=<optimized out>, record=record@entry=0x2aead0442078 "\377\367\377", data=data@entry=0x1 <Address 0x1 out of bounds>) at \
/home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc:2588
#7  0x00002aea9306644f in ha_tokudb::unpack_key (this=this@entry=0x2aeadafc7078, record=0x2aead0442078 "\377\367\377", key=key@entry=0x2aeabeab4828, index=0) at /home/tokubuild/builds/build-tokudb-7.1.5-\
rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc:2608
#8  0x00002aea930664f2 in ha_tokudb::set_dup_value_for_pk (this=0x2aeadafc7078, key=key@entry=0x2aeabeab4828) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_to\
kudb.cc:8238
#9  0x00002aea93066573 in loader_dup_fun (db=<optimized out>, i=<optimized out>, err=-30996, key=0x2aeabeab4828, val=<optimized out>, error_extra=0x2aeadafc88b0) at /home/tokubuild/builds/build-tokudb-7.\
1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc:518
#10 0x00002aea930bde47 in ft_loader_call_error_function (loader_error=0x2aeabeab4800) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ft-index/ft/ftloader-callback\
.cc:167
#11 0x00002aea930bd031 in toku_ft_loader_close (bl=0x2aeabeab4800, error_function=<optimized out>, error_extra=<optimized out>, poll_function=0x2aea9304d289 <loader_poll_fun(void*, float)>, poll_extra=0x\
2aeadafc88b0) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ft-index/ft/ftloader.cc:2858
#12 0x00002aea9308a7d2 in ft_loader_close_and_redirect (loader=0x2aeacffbab20) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ft-index/src/loader.cc:216
#13 0x00002aea9308b35b in toku_loader_close (loader=0x2aeacffbab20) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ft-index/src/loader.cc:469
#14 0x00002aea9306c070 in ha_tokudb::end_bulk_insert (this=0x2aeadafc7078, abort=abort@entry=false) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc:33\
27
#15 0x00002aea9306c4dc in ha_tokudb::end_bulk_insert (this=<optimized out>) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc:3391
#16 0x0000000000619248 in ha_end_bulk_insert (this=0x2aeadafc7078) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/handler.h:2220
#17 copy_data_between_tables (error_if_not_empty=false, keys_onoff=(unknown: 3330199904), deleted=<synthetic pointer>, copied=<synthetic pointer>, order=0x0, order_num=0, ignore=120, create=..., to=0x2ae\
ad0441260, from=0x2aead1bb5e60, thd=0x2aea8de87060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/sql_table.cc:7737
#18 mysql_alter_table (thd=<optimized out>, new_db=<optimized out>, new_name=0x2aeabe85a1a8 "table100_tokudb_tokudb_small", create_info=0x2aeb2c846260, table_list=0x3e8, alter_info=0x2aeb2c8461c0, order_\
num=0, order=0x0, ignore=false, require_online=false) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/sql_table.cc:6941
#19 0x00000000006643c1 in Alter_table_statement::execute (this=<optimized out>, thd=0x2aea8de87060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/sql_alter.cc:106
#20 0x000000000059c3d9 in mysql_execute_command (thd=thd@entry=0x2aea8de87060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/sql_parse.cc:4526
#21 0x000000000059d7c5 in mysql_parse (thd=thd@entry=0x2aea8de87060, rawbuf=<optimized out>, length=<optimized out>, parser_state=parser_state@entry=0x2aeb2c847870) at /home/tokubuild/builds/build-tokudb\
-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/sql_parse.cc:5813
#22 0x000000000059e356 in dispatch_command (command=command@entry=COM_QUERY, thd=thd@entry=0x2aea8de87060, packet=packet@entry=0x2aea8de8c061 "ALTER TABLE `table100_tokudb_tokudb_small` ADD PRIMARY KEY (\
c2) USING HASH", packet_length=packet_length@entry=74) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/sql/sql_parse.cc:1082
```

```
(gdb) 
#9  0x00002aea93066573 in loader_dup_fun (db=<optimized out>, i=<optimized out>, err=-30996, key=0x2aeabeab4828, val=<optimized out>, error_extra=0x2aeadafc88b0) at /home/tokubuild/builds/build-tokudb-7.\
1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc:518
518     in /home/tokubuild/builds/build-tokudb-7.1.5-rc.1-debug-e/mariadb-5.5.35/storage/tokudb/ha_tokudb.cc
(gdb) p *key
$1 = {data = 0x0, size = 0, ulen = 0, flags = 0}
```

**Comment by prohaska** [comment]
i ran the alter table statement on table100_tokudb_tokudb_small table in the rundir1_163 successfully.

**Comment by prohaska** [comment]
the tokudb loader passes an uninitialized key to tokudb.  wrong.

tokudb blew up when trying to handle the uninitialized key.  wrong.

**Comment by tmcallaghan** [comment]
Moved to Jira as https://tokutek.atlassian.net/browse/DB-526
