### ISSUE TITLE
MDEV-5743 RQG test alter_online.yy causes segmentation fault and crash

### ISSUE THREAD

**Issue by joel9001** [Tokutek/mariadb-5.5#48]
During an RQG suites run, alter_online.yy causes a seg fault and crash.  Here is the command that causes the crash:

```
./runall.pl --grammar=conf/runtime/alter_online.yy --duration=300 --queries=100000000 --threads=64 --basedir=/mnt/ssd/mysql/mariadb-5.5.35-tokudb-7.1.5-rc.3-debug-e-linux-x86_64 --vardir=/mnt/ssd/mysql/vardir1 --mask-level=0 --mask=0 --seed=1 --mysqld=--general_log
```

**Comment by joel9001** [comment]
```
140225 22:43:46 [ERROR] mysqld got signal 11 ;

Server version: 5.5.35-tokudb-7.1.5-rc.3-debug-e-MariaDB-debug-log
key_buffer_size=1048576
read_buffer_size=131072
max_used_connections=55
max_threads=153
thread_count=55
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 62571 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0x7ff6ad6cc060
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7ff6c8389e28 thread_stack 0x48000
mysys/stacktrace.c:246(my_print_stacktrace)[0xb879c8]
sql/signal_handler.cc:155(handle_fatal_signal)[0x6ecb94]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xfbb0)[0x7ff6c8f80bb0]
sql/sql_table.cc:7031(mysql_alter_table(THD*, char*, char*, st_ha_create_information*, TABLE_LIST*, Alter_info*, unsigned int, st_order*, bool, bool))[0x6196c0]
sql/sql_alter.cc:106(Alter_table_statement::execute(THD*))[0x6643c1]
sql/sql_parse.cc:4526(mysql_execute_command(THD*))[0x59c3d9]
sql/sql_parse.cc:5813(mysql_parse(THD*, char*, unsigned int, Parser_state*))[0x59d7c5]
sql/sql_parse.cc:1072(dispatch_command(enum_server_command, THD*, char*, unsigned int))[0x59e356]
sql/sql_parse.cc:797(do_command(THD*))[0x59fbaa]
sql/sql_connect.cc:1266(do_handle_one_connection(THD*))[0x660fc6]
sql/sql_connect.cc:1183(handle_one_connection)[0x6610b8]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7f6e)[0x7ff6c8f78f6e]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ff6c869b9cd]
Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7ff68b825078): ALTER TABLE t1 ADD PRIMARY KEY ( col4(10) )
Connection ID (thread ID): 8
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=off

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
Attempting to use gdb @[/usr/bin/gdb] on pid[13983]
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
/mnt/ssd/mysql/vardir1/master-data/13983: No such file or directory.
No thread selected
No stack.
No stack.
Writing a core file

2014-02-25T14:43:49 datadir is /mnt/ssd/mysql/vardir1/master-data/
```

**Comment by joel9001** [comment]
```
2014-02-25T14:43:50 Core was generated by `/mnt/ssd/mysql/mariadb-5.5.35-tokudb-7.1.5-rc.3-debug-e-linux-x86_64/bin/mysqld'.
2014-02-25T14:43:50 Program terminated with signal 11, Segmentation fault.
2014-02-25T14:43:50 #0  0x00007ff6c8f7df0c in __pthread_kill (threadid=<optimized out>, signo=signo@entry=11) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:62
2014-02-25T14:43:50 #0  0x00007ff6c8f7df0c in __pthread_kill (threadid=<optimized out>, signo=signo@entry=11) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:62
2014-02-25T14:43:50 #1  0x0000000000b878c3 in my_write_core (sig=11) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/mysys/stacktrace.c:457
2014-02-25T14:43:50 #2  0x00000000006ece0a in handle_fatal_signal (sig=11) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/signal_handler.cc:264
2014-02-25T14:43:50 #3  <signal handler called>
2014-02-25T14:43:50 #4  0x00000000006196c0 in mysql_alter_table (thd=thd@entry=0x7ff6ad6cc060, new_db=<optimized out>, new_name=0x0, create_info=create_info@entry=0x7ff6c8387fe0, table_list=0x7ff68b826300, table_list@entry=0x7ff68b825180, alter_info=alter_info@entry=0x7ff6c8387f40, order_num=0, order=0x0, ignore=false, require_online=false) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_table.cc:7031
2014-02-25T14:43:50 #5  0x00000000006643c1 in Alter_table_statement::execute (this=<optimized out>, thd=0x7ff6ad6cc060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_alter.cc:106
2014-02-25T14:43:50 #6  0x000000000059c3d9 in mysql_execute_command (thd=thd@entry=0x7ff6ad6cc060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_parse.cc:4526
2014-02-25T14:43:50 #7  0x000000000059d7c5 in mysql_parse (thd=thd@entry=0x7ff6ad6cc060, rawbuf=<optimized out>, length=<optimized out>, parser_state=parser_state@entry=0x7ff6c83895f0) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_parse.cc:5813
2014-02-25T14:43:50 #8  0x000000000059e356 in dispatch_command (command=command@entry=COM_QUERY, thd=thd@entry=0x7ff6ad6cc060, packet=packet@entry=0x7ff6ad6d1061 "ALTER TABLE t1 ADD PRIMARY KEY ( col4(10) )", packet_length=packet_length@entry=43) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_parse.cc:1082
2014-02-25T14:43:50 #9  0x000000000059fbaa in do_command (thd=0x7ff6ad6cc060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_parse.cc:797
2014-02-25T14:43:50 #10 0x0000000000660fc6 in do_handle_one_connection (thd_arg=thd_arg@entry=0x7ff6ad6cc060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_connect.cc:1266
2014-02-25T14:43:50 #11 0x00000000006610b8 in handle_one_connection (arg=0x7ff6ad6cc060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_connect.cc:1181
2014-02-25T14:43:50 #12 0x00007ff6c8f78f6e in start_thread (arg=0x7ff6c838a700) at pthread_create.c:311
2014-02-25T14:43:50 #13 0x00007ff6c869b9cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
2014-02-25T14:43:50 #5  0x00000000006643c1 in Alter_table_statement::execute (this=<optimized out>, thd=0x7ff6ad6cc060) at /home/tokubuild/builds/build-tokudb-7.1.5-rc.3-debug-e/mariadb-5.5.35/sql/sql_alter.cc:106
2014-02-25T14:43:50 101       in /home/tokubuild/builds/build-tokudb-7.1.5-rc
```

**Comment by prohaska** [comment]
problem occurs with an innodb table and is reproducible with the data directory created by runall.pl.

```
mysql> show create table t1;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                   |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `col4` text NOT NULL,
  `col2` int(11) DEFAULT NULL,
  `col1` int(11) DEFAULT NULL,
  `col3` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

**Comment by elenst** [comment]
Refiled as https://mariadb.atlassian.net/browse/MDEV-5743
Test case is in the JIRA bug report.

**Comment by prohaska** [comment]
fixedin 5.5.37

**Comment by joel9001** [comment]
Using mysql-5.5.37-tokudb-7.1.6-debug-e-linux-x86_64, this issue appears to be fixed based on the test case reduced in MDEV-5743.  

Here are the results:

mysql> use test;
Database changed
mysql> CREATE TABLE t1 (a INT) ENGINE = InnoDB;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (2);
Query OK, 1 row affected (0.00 sec)

mysql> ALTER TABLE t1 ADD PRIMARY KEY (a);
Query OK, 1 row affected (0.00 sec)
Records: 1  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE t1 DROP PRIMARY KEY;
Query OK, 1 row affected (0.01 sec)
Records: 1  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t1 VALUES (2);
Query OK, 1 row affected (0.00 sec)

mysql> ALTER TABLE t1 ADD PRIMARY KEY (a);
ERROR 1062 (23000): Duplicate entry '2' for key 'PRIMARY'
mysql>
